### ISSUE TITLE
Can't tab complete

### ISSUE THREAD

**Issue by acrylic-style** [rht0910/PluginManager#85]
![image](https://user-images.githubusercontent.com/19150229/46913013-f3282e00-cfbf-11e8-8861-b1b1d22b81c7.png)

**Comment by acrylic-style** [comment]
```
[14:46:07 WARN]: §r[PluginManager] §r&cエラーが発生しました: %s
[14:46:07 WARN]: java.lang.ArrayIndexOutOfBoundsException: 2
[14:46:07 WARN]:        at tk.rht0910.plugin_manager.PluginManager.onCommand(PluginManager.java:514)
[14:46:07 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[14:46:07 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[14:46:07 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:699)
[14:46:07 WARN]:        at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1646)
[14:46:07 WARN]:        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1481)
[14:46:07 WARN]:        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45)
[14:46:07 WARN]:        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1)
[14:46:07 WARN]:        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10)
[14:46:07 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
[14:46:07 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[14:46:07 WARN]:        at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199)
[14:46:07 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900)
[14:46:07 WARN]:        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
[14:46:07 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835)
[14:46:07 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733)
[14:46:07 WARN]:        at java.base/java.lang.Thread.run(Thread.java:844)
[14:46:12 ERROR]: Exception when Lang_Crasher attempted to tab complete pman config language
org.bukkit.command.CommandException: Unhandled exception during tab completion for command '/pman config language' in plugin PluginManager v1.4.3
        at org.bukkit.command.PluginCommand.tabComplete(PluginCommand.java:144) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-e3d7b2f]
        at org.bukkit.command.Command.tabComplete(Command.java:90) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-e3d7b2f]
        at org.bukkit.command.SimpleCommandMap.tabComplete(SimpleCommandMap.java:217) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-e3d7b2f]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.tabCompleteCommand(CraftServer.java:1690) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-e3d7b2f]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.tabComplete(CraftServer.java:1662) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-e3d7b2f]
        at org.bukkit.craftbukkit.v1_13_R2.command.BukkitCommandWrapper.getSuggestions(BukkitCommandWrapper.java:49) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-e3d7b2f]
        at com.mojang.brigadier.tree.ArgumentCommandNode.listSuggestions(ArgumentCommandNode.java:68) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-e3d7b2f]
        at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:379) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-e3d7b2f]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:514) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-e3d7b2f]
        at net.minecraft.server.v1_13_R2.PacketPlayInTabComplete.a(SourceFile:36) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-e3d7b2f]
        at net.minecraft.server.v1_13_R2.PacketPlayInTabComplete.a(SourceFile:9) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-e3d7b2f]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-e3d7b2f]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.1.jar:git-Spigot-f6a273b-e3d7b2f]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [spigot-1.13.1.jar:git-Spigot-f6a273b-e3d7b2f]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.1.jar:git-Spigot-f6a273b-e3d7b2f]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot-1.13.1.jar:git-Spigot-f6a273b-e3d7b2f]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot-1.13.1.jar:git-Spigot-f6a273b-e3d7b2f]
        at java.lang.Thread.run(Thread.java:844) [?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 2
        at tk.rht0910.plugin_manager.PluginManager.onTabComplete(PluginManager.java:180) ~[?:?]
        at org.bukkit.command.PluginCommand.tabComplete(PluginCommand.java:135) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-e3d7b2f]
        ... 19 more
```

**Comment by acrylic-style** [comment]
why is it abondoned lol

**Comment by acrylic-style** [comment]
This plugin is now deprecated and you should not use this plugin.
